---
title: বিবিধ অপলাপ
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: বোধি, বিষাদ এবং নক্ষত্রজাত বাজপাখির হাহাকার
email: uroybd@gmail.com
description: আমি উৎসব রায়। আর সব মানুষের মতই নক্ষত্রজাত। কবিতা লিখতে ভালোবাসি, কোড
  করতেও। আমার বোধি ও বিষাদ আছে। আর যদি পৃথিবীর খুব উঁচুতে ডানা মেলি, তবে যুদ্ধ, মৃত্যু
  আর ধ্বংস দেখি।
baseurl: ''
url: https://thoughts.utsob.me
gems:
- jemoji
- jekyll-paginate
- jekyll-sass
- jekyll-sitemap
paginate: 5
paginate_path: "/page:num/"
logo: "/images/weblogo.jpg"
github_username: uroybd
disqus: uroybdgit
markdown: kramdown
highlighter: rouge
kramdown:
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
author:
  name: উৎসব রায়(Utsob Roy)
  image: "/images/me.jpg"
  bio: কবি ও কোডার
  website: https://utsob.me/
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings:
  - html
  - head
  - body
fb_app_id: '1748437412133225'
fb_username: uroybd
first_name: উৎসব
last_name: রায়
gender: male
